runtime: python311

automatic_scaling:
  target_cpu_utilization: 0.65
  min_idle_instances: 1
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

inbound_services:
- warmup

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker __init__:app
